name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check:
    name: check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Install
        run: npm install --legacy-peer-deps

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test